<br>

# <center><b>WEEK - 10</b></center>

<br>


---
---

# <b>FLAMES</b><br>

---

---


![Alt text](image.png)


![Alt text](image-1.png)


![Alt text](image-3.png)


![Alt text](image-4.png)


![Alt text](image-5.png)


![Alt text](image-2.png)


In [22]:
import string

str = "Avinash Yadav"

print("String: ", str)
print("Lower Case: ", str.lower())
print("Upper Case: ", str.upper())
print("Capitalize Case: ", str.capitalize())

print()
print()


str_list = list(str)
print(str_list)

print(str_list.index(" "))
print(str_list.index("v"))          # Return first index of value occurance.
# Raises ValueError if the value is not present
# print(str_list.index("V"))          # ValueError: 'V' is not in list

# Return a copy with all occurrences of substring old replaced by new.
print(str.replace(" ", "@"))
print(str.replace("a", "#"))        # Maximum number of occurrences to replace.
# -1 (the default value) means replace all occurrences.
# If the optional argument count is given, only the first count occurrences are replaced.
print(str.replace("v", "$", 1))
print(str.replace("v", "$", -1))

String:  Avinash Yadav
Lower Case:  avinash yadav
Upper Case:  AVINASH YADAV
Capitalize Case:  Avinash yadav


['A', 'v', 'i', 'n', 'a', 's', 'h', ' ', 'Y', 'a', 'd', 'a', 'v']
7
1
Avinash@Yadav
Avin#sh Y#d#v
A$inash Yadav
A$inash Yada$


In [ ]:
def remove_matching_letters(list_player_1, list_player_2):

    # Iterating through player_1 name list:
    for i in range(len(list_player_1)):

        # Iterating through player_2 name list:
        for j in range(len(list_player_2)):

            # Checking the each letters from both the list
            if list_player_1[i] == list_player_2[j]:
                common = list_player_1[i]
                list_player_1.remove(common)
                list_player_2.remove(common)

                concat_list = list_player_1 + ['*'] + list_player_2
                return [concat_list, True]

    concat_list = list_player_1 + ['*'] + list_player_2
    return [concat_list, False]


# Taking user name as input
# Converting all the letters in the name in lower case
# Replacing/Removing the empty spaces
player_1 = input("Enter Your Name Player_1: ").lower().replace(" ", "")
print(player_1)

player_2 = input("Enter Your Name Player_2: ").lower().replace(" ", "")
print(player_2)


# Converting the player name in list of character
list_player_1 = list(player_1)
list_player_2 = list(player_2)


proceed = True
while proceed:
    returned_list = remove_matching_letters(list_player_1, list_player_2)
    concat_list = returned_list[0]
    proceed = concat_list[1]
    star_index = concat_list.index('*')
    list_player_1 = concat_list[: star_index]
    list_player_2 = concat_list[star_index+1:]


count = len(list_player_1) + len(list_player_2)

result = ['Friend', 'Love', 'Affection', 'Marriage', 'Enemy', 'Siblings']

while len(result) > 1:
    split_index = (count % len(result)) - 1

    if split_index >= 0:
        right = result[split_index+1:]
        left = result[: split_index]
        result = right + left

    else:
        result = result[:len(result)-1]


print("The relationship between Player 1 and Player 2 is:", result[0])

<br><br><br><br><br><br>

---

---

# <b>DATA COMPRESSION</b><br>

---

---


![Alt text](image-7.png)


![Alt text](image-6.png)


## BASIC OVERVIEW OF NUMPY LIBRARY:


In [26]:
import numpy as np

print("----------------------------")
print()

arr1 = np.array([1, 2, 3])

print(arr1)
print()

print(type(arr1))
print()

print(arr1.dtype)
print()

print(arr1.shape)
print()

print(arr1[1])
print()

arr1[1] = 100
print(arr1[1])
print()
print("----------------------------")
print()


arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr2)
print()

print(type(arr2))
print()

print(arr2.shape)
print()

print(arr2[1])
print()

arr2[1] = 100
print(arr2[1])
print()
print("----------------------------")
print()

----------------------------

[1 2 3]

<class 'numpy.ndarray'>

int32

(3,)

2

100

----------------------------

[[1 2 3]
 [4 5 6]]

<class 'numpy.ndarray'>

(2, 3)

[4 5 6]

[100 100 100]

----------------------------



In [32]:
arrZERO = np.zeros((2, 2))
print(arrZERO)
print(arrZERO.dtype)
print()

arrONE = np.ones((2, 2))
print(arrONE)
print(arrONE.dtype)
print()

arrFULL1 = np.full((2, 2), 10)
print(arrFULL1)
print(arrFULL1.dtype)
print()

arrFULL2 = np.full((2, 2), 10, dtype=np.int64)
print(arrFULL2)
print(arrFULL2.dtype)
print()

arrRANDOM = np.random.random((2, 2))
print(arrRANDOM)
print(arrRANDOM.dtype)

[[0. 0.]
 [0. 0.]]
float64

[[1. 1.]
 [1. 1.]]
float64

[[10 10]
 [10 10]]
int32

[[10 10]
 [10 10]]
int64

[[0.1431192  0.51822074]
 [0.32565461 0.02721341]]
float64


In [48]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

print("X = \n", x)
print()

print("Y = \n", y)
print()

print("X + Y = \n", x+y)
print()

print("X + Y = \n", np.add(x, y))
print()

print("X - Y = \n", x-y)
print()

print("X - Y = \n", np.subtract(x, y))
print()

print("X * Y = \n", np.multiply(x, y))
print()

print("X / Y = \n", np.divide(x, y))

X = 
 [[1. 2.]
 [3. 4.]]

Y = 
 [[5. 6.]
 [7. 8.]]

X + Y = 
 [[ 6.  8.]
 [10. 12.]]

X + Y = 
 [[ 6.  8.]
 [10. 12.]]

X - Y = 
 [[-4. -4.]
 [-4. -4.]]

X - Y = 
 [[-4. -4.]
 [-4. -4.]]

X * Y = 
 [[ 5. 12.]
 [21. 32.]]

X / Y = 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


## LOSSY IMAGE COMPRESSION


![Alt text](image-8.png)


In [ ]:
import numpy as np
from PIL import Image

# Original size of the image before compression: 324.7 kb
im = Image.open("image-8.png")

pixelMap = im.load()

image_matrix = np.array(Image.open("image-8.png"))
# print(image_matrix)

# Creating a new image with the same size as the original image:
img = Image.new(im.mode, im.size)

pixelNew = img.load()

'''
2^8 = 256
2^5 = 32

0-31 = 0
32-63 = 1
64-95 = 2
96-127 = 3
128-159 = 4
160-191 = 5
192-223 = 6
224-255 = 7
'''

for i in range(img.size[0]):
    for j in range(img.size[1]):
        if (pixelMap[i, j] >= 0 and pixelMap[i, j] <= 31):
            pixelNew[i, j] = 0

        elif (pixelMap[i, j] >= 32 and pixelMap[i, j] <= 63):
            pixelNew[i, j] = 1

        elif (pixelMap[i, j] >= 64 and pixelMap[i, j] <= 95):
            pixelNew[i, j] = 2

        elif (pixelMap[i, j] >= 96 and pixelMap[i, j] <= 127):
            pixelNew[i, j] = 3

        elif (pixelMap[i, j] >= 128 and pixelMap[i, j] <= 159):
            pixelNew[i, j] = 4

        elif (pixelMap[i, j] >= 160 and pixelMap[i, j] <= 191):
            pixelNew[i, j] = 5

        elif (pixelMap[i, j] >= 192 and pixelMap[i, j] <= 223):
            pixelNew[i, j] = 6

        elif (pixelMap[i, j] >= 224 and pixelMap[i, j] <= 255):
            pixelNew[i, j] = 7

img.save("compressedIMG.png")

compressedImage = np.asanyarray(Image.open("compressedIMG.png"))

<br><br><br><br><br><br><br><br>

---
---

> <br><br><br><br>
>
> # <center><b>Week 10: Assignment</b></center>
>
> <br><br><br><br>

---

---


## <center><b>QUESTION - 01</b></center>


# D

In [67]:
s = "Hello Everyone"
print(s.lower())

hello everyone


## <center><b>QUESTION - 02</b></center>


# A

## <center><b>QUESTION - 03</b></center>


# C

In [68]:
a = ['', 'h', 'e', 'l', '', 'l', 'o']
print('.'.join(a))

.h.e.l..l.o


## <center><b>QUESTION - 04</b></center>


# D

In [72]:
s = 'The joy of Computing'

s = s.replace('a' , '_')
s = s.replace('e' , '_')
s = s.replace('i' , '_')
s = s.replace('o' , '_')
s = s.replace('u' , '_')

print(s)

Th_ j_y _f C_mp_t_ng


## <center><b>QUESTION - 05</b></center>


# B

In [73]:
s = 'The Joy of Computing'

print(s[3:12])

 Joy of C


## <center><b>QUESTION - 06</b></center>


# C

In [75]:
s = 'Sheher mein'
a = 'aeiouAEIOU'
for i in range(len(s)):
    if(s.index(s[i])%2 == 0):
        print(i)
        if(s[i] in a):
            s = s.replace(s[i], '_')
            
print(s)

0
2
4
6
8
10
Sh_h_r m_in


## <center><b>QUESTION - 07</b></center>


# B

In [76]:
import numpy as np

b = np.array([[1, 2], [3, 4]])

print(np.sum(b, axis = 1))

[3 7]


## <center><b>QUESTION - 08</b></center>


# C

In [77]:
import numpy as np

b = b = np.array([[1, 2], [3, 4]])

print(b.T)

[[1 3]
 [2 4]]


## <center><b>QUESTION - 09</b></center>

# B

## <center><b>QUESTION - 10</b></center>


# A

In [78]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)

(2, 3)


## <center><b>QUESTION - 11</b></center>


# C

In [79]:
import numpy as np

a = np.array([[8, 9, 20], [10, 31, 22]])
b = np.array([[1, 2, 3], [4, 5, 6]])

print(a-b)

[[ 7  7 17]
 [ 6 26 16]]


<br><br><br><br>

---
---

<br><br>

# <center><b> PROGRAMMING ASSIGNMENT - 01:</b></center>

<br><br>


<br><br><br><br>

---
---

<br><br>

# <center><b> PROGRAMMING ASSIGNMENT - 02:</b></center>

<br><br>


<br><br><br><br>

---
---

<br><br>

# <center><b> PROGRAMMING ASSIGNMENT - 03:</b></center>

<br><br>
